apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-bot
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nodejs-bot
  template:
    metadata:
      labels:
        app: nodejs-bot
    spec:
      containers:
      - name: bot-container
        image: ghcr.io/egorpirkov/training-tg-bot:sha-149c290
